# SPDX-FileCopyrightText: 2026 LibreCode coop and contributors
#
# SPDX-License-Identifier: AGPL-3.0-or-later

version = 1
SPDX-PackageName = "nfse-php"
SPDX-PackageSupplier = "LibreCode Coop <dev@librecodecoop.org.br>"
SPDX-PackageDownloadLocation = "https://github.com/LibreCodeCoop/nfse-php"

default-license = "AGPL-3.0-or-later"
default-copyright = "2026 LibreCode coop and contributors"

[[annotations]]
path = [
    ".gitignore",
    "composer.json",
    "vendor-bin/domains/composer.json",
    "vendor-bin/domains/composer.lock",
    "resources/domains/sources.json"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2026 LibreCode coop and contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = [
    "references/schemas/nfse/1.01/*.xsd"
]
precedence = "override"
SPDX-FileCopyrightText = "Sistema Nacional NFS-e / Governo Federal"
SPDX-License-Identifier = "CC-BY-ND-3.0"

[[annotations]]
path = [
    "resources/domains/*.tsv",
    "resources/contracts/*.tsv"
]
precedence = "override"
SPDX-FileCopyrightText = "Sistema Nacional NFS-e / Governo Federal"
SPDX-License-Identifier = "CC-BY-ND-3.0"
