# SPDX-FileCopyrightText: 2026 LibreCode coop and contributors
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Minimum Dependencies

on: pull_request

permissions:
  contents: read

concurrency:
  group: minimum-dependencies-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  minimum-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up PHP from Composer
        uses: ./.github/actions/setup-project-php
        with:
          extensions: openssl, dom, soap
          ini-file: development
          ini-values: disable_functions=
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Resolve minimum supported dependencies
        run: composer update --prefer-lowest --prefer-stable --prefer-dist --no-progress

      - name: Run unit tests
        env:
          NFS_TEST_CNPJ: "11222333000181"
          NFS_SANDBOX: "true"
        run: composer run test:unit
